Instructions for additional Line following Lab Exercise
lf-lang/lf-pico pull request #22
Opened 2024-02-09 19:09 UTC by hokeun

2024-02-17 03:04 UTC, edwardalee requested changes
This looks like a good start.  One high-level comment:

Line following applications that I've seen before use a thin line and use the sensors to try to keep the center sensors over the dark part and the outside sensors over the light part.

It looks like what you have implemented is "track following" rather than "line sensing", since your goal seems to be stay within the track.

2024-02-17 03:04 UTC, edwardalee commented on src/Line.md
> +The goal of this exercise is to do LF programming using the Pololu robot to execute a specified task, namely line follwoing, where the robot detects the line and follows the line until it reaches the
```suggestion
The goal of this exercise is to program the Pololu robot in LF to perform line following, where the robot detects a line and follows it until it reaches the end.
```

2024-02-17 03:04 UTC, edwardalee commented on src/Line.md
> +- Review the section for the motors from the previous lab. This lab will test you how to adjust power to maneuver curves and sharp turns.
```suggestion
- Review the section for the motors from the previous lab. This lab will test how you adjust power to maneuver curves and sharp turns.
```

2024-02-17 03:04 UTC, edwardalee commented on src/Line.md
> +- Review line sensing, the same calibration should be done at the beginning of this excersie as well. However, there is a small difference in how the sensor is calibrated.
Where is "line sensing"?  Hyperlink here?  Also:
```suggestion
- Review line sensing. The same calibration should be done at the beginning of this exercise, however, with a small difference, explained below.
```

2024-02-17 03:04 UTC, edwardalee commented on src/Line.md
> +   For this lab, you are required to indicate where the robot is going to move as the sensor moves out of the line in order for the robot to realign itself with the track.
The above sentence is not clear.  What does it mean to "indicate where the robot is going"?

2024-02-17 03:04 UTC, edwardalee commented on src/Line.md
> +Write LF code to make your robot follow the designated path. The trick is to make sure the robot's motor is calibrated perfectly to make the turns, adjust the speed of the robot.
This is worrisome. Perfect calibration is not possible.

2024-02-17 03:04 UTC, edwardalee commented on src/Line.md
> +**HINT:** 0.1f would be perfect to start, you may increase or decrease the speed eventually. The goal is functionality.
I think "perfect" can't be right here.  You mean that this is a reasonable guess?  Also, there are two motors.  What does it mean to calibrate them?  Are you referring to speed here rather than calibration?

2024-02-17 03:04 UTC, edwardalee commented on src/Line.md
> +You may build a track at your own home, to test your code. The important thing to keep in mind is that the track must be smooth and the robot should not get stuck somewhere in between. The key thing
```suggestion
You may build a track at your own to test your code. The important thing to keep in mind is that the track must be smooth and the robot should not get stuck somewhere on the track. The track and the surroundings must have a significant contrast in color. You are free to test your code on that track before you submit the code. The robot should align itself without any external help even if it starts out skewed with respect to the track. The robot should stop at the end of the track or continue indefinitely if the track forms a loop. The robot should have enough intelligence or functionality to keep itself on track. The robot will be tested on a different track from the one you developed your code with, to ensure adaptability. Please put your solution in a file called `LineFollowSolution.lf`.
```

2024-02-17 03:04 UTC, edwardalee commented on src/Line.md
> +**Checkoff:** Show your robot driving to the end of the line, handling the curves smoothly.
```suggestion
**Checkoff:** Show your robot driving to the end of the line and handling the curves smoothly.
```

2024-02-18 01:19 UTC, hokeun commented on src/Line.md
> +- Review line sensing, the same calibration should be done at the beginning of this excersie as well. However, there is a small difference in how the sensor is calibrated.
Thank you for catching this! Fixed this in 88158b927f042547166f98051f2196eb9ab172d0.

2024-02-20 16:12 UTC, the-systematic-chaos commented on src/Line.md
> +   For this lab, you are required to indicate where the robot is going to move as the sensor moves out of the line in order for the robot to realign itself with the track.
I have changed it to "indicate where the robot is planning or programmed to move" in the latest commit. I have also added a brief explanation in brackets.

2024-02-20 16:12 UTC, the-systematic-chaos commented on src/Line.md
> +Write LF code to make your robot follow the designated path. The trick is to make sure the robot's motor is calibrated perfectly to make the turns, adjust the speed of the robot.
Oh yes you're right, that was worded incorrectly, I have made the change as :  "make sure the speed of the robot's motor enables it to maneuver the turns, adjust the speed of the robot if necessary"

2024-02-20 16:12 UTC, the-systematic-chaos commented on src/Line.md
> +**HINT:** 0.1f would be perfect to start, you may increase or decrease the speed eventually. The goal is functionality.
Yes I was referring to the speed, I have changed it to: "0.1f would be a reasonable starting point for the speed".
Thank you for the comments, I have made the changes necessary.

2024-03-02 17:57 UTC, edwardalee approved these changes
LGTM.  Minor suggestions for wording and redundancy.

2024-03-02 17:57 UTC, edwardalee commented on src/Line.md
> +You may build a track at your own home to test your code. The important thing to keep in mind is that the track must be smooth, and the robot should not get stuck somewhere in between. The key thing
```suggestion
You may build a track at your own home to test your code. The important thing to keep in mind is that the track must be smooth, and the robot should not get stuck somewhere in between. The key thing is that the track and the surroundings must have a significant contrast in terms of color. You are free to test your code on that track before you submit the code for it. The robot should align itself without any external help, even if it starts out skewed with respect to the track. The robot should stop at the end of the track or keep continuing if the track is a loop. You are free to include any module of your choice to make sure the robot is precise in keeping itself on track, and the robot should have enough intelligence or functionality to keep itself on track. The robot will be tested on a different track from the one you developed your code with to ensure uniformity. Please put your solution in a file called `TrackFollowSolution.lf`.
```

2024-03-08 19:02 UTC, hokeun commented
> LGTM. Minor suggestions for wording and redundancy.

Thank you for your feedback!

2024-03-08 19:03 UTC, merged